# Generated by Django 5.1.2 on 2025-09-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalBank', '0003_banktransaction_balance_before_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='transaction_account',
            new_name='transfer_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_account',
            new_name='transfer_account',
        ),
    ]
